function(includePlatform name)
  set(_platform_file "${CMAKE_CURRENT_LIST_DIR}/platform/${name}.cmake")
  if(EXISTS "${_platform_file}")
    include("${_platform_file}")
  else()
    message(STATUS "No platform include found for '${name}', skipping.")
  endif()
endfunction()

function(collect_files out_var base_dir recursive patterns exclude_paths)
  if(recursive)
    file(GLOB_RECURSE _collected "${base_dir}/${patterns}")
  else()
    file(GLOB _collected "${base_dir}/${patterns}")
  endif()

  set(_exclusions ${exclude_paths})
  foreach(_exclude IN LISTS _exclusions)
    if(_exclude)
      list(FILTER _collected EXCLUDE REGEX "${_exclude}")
    endif()
  endforeach()

  set(${out_var} ${_collected} PARENT_SCOPE)
endfunction()

function(assign_specific_source_group group)
  if(ARGC GREATER 1)
    set(_files ${ARGV})
    list(REMOVE_AT _files 0)
    if(_files)
      source_group("${group}" FILES ${_files})
    endif()
  endif()
endfunction()

function(assign_source_group)
  foreach(_list IN LISTS ARGN)
    if(_list)
      source_group(TREE "${CMAKE_SOURCE_DIR}" FILES ${_list})
    endif()
  endforeach()
endfunction()

# Some legacy variables expected by the root CMakeLists.txt
set(force_update_file "" CACHE INTERNAL "Placeholder for legacy build hooks")
